### PR TITLE
Fix alias_method_chain deprecation

### PR DESCRIPTION
**Pull request by dalibor**
TODO: Needs more testing in live environment to see if we get the issue fixed in https://github.com/dalibor/octoshark/pull/15.

### CODE REVIEW

**Comment by jnstq** [comment]
Will this be merged?

**Comment by dalibor** [comment]
@jnstq I will merge, but this fix is not good enough as it stands now. I'm getting an error when running Rails 4.2 app with Passenger, but not when running the same app with thin server. Will need to investigate what's up with that.

**Comment by jnstq** [comment]
@dalibor Got it, thanks! Just found your project today, this is exactly what we need 👍

**Comment by dalibor** [comment]
@jnstq Cool. :smile: I think I have this fixed. Will give it a test run in production tomorrow and if things are good I will release a new gem version.

**Comment by jnstq** [comment]
Super, I will try it in our rails 5 branch tomorrow.

**Comment by dalibor** [comment]
This looks good in test and production, I'm merging.

**Pull request merged**
